<svelte:head>
	<title>Detailed Design - ZeroVerify</title>
</svelte:head>

<div class="design-page">
	<h1>Detailed Component Design</h1>
	<p class="subtitle">Database schemas, API specifications, and algorithm logic</p>

	<section class="section">
		<h2>Overview</h2>
		<p class="lead">
			This page provides the technical deep dive into ZeroVerify's component-level design,
			including data models, API contracts, and the zero-knowledge proof circuits that power
			privacy-preserving verification.
		</p>
	</section>

	<section class="section" id="database">
		<h2>Database Schema</h2>

		<div class="schema-card">
			<h3>Credential Metadata Table (DynamoDB)</h3>
			<p class="schema-description">
				Stores metadata about issued credentials. The actual credential data is never stored on our servers.
			</p>

			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Table Structure</span>
					<span class="code-lang">DynamoDB</span>
				</div>
				<pre><code>{`{
  "subject_id": "did:key:z6MkF5rGMoatr...",           // Partition key
  "credential_id": "a3f8b2c1-4d5e-6f7a-8b9c-...",    // Sort key (UUID)
  "credential_type": "Student_Credential",
  "issued_at": "2025-02-10T20:41:27Z",               // ISO 8601
  "expiresAt": "2026-02-10T20:41:27Z",
  "revocation_index": 94567,                         // Position in bitstring
  "revoked": false                                    // Status
}`}</code></pre>
			</div>

			<div class="schema-details">
				<h4>Field Descriptions</h4>
				<ul>
					<li><strong>subject_id:</strong> Pseudonymous user identifier (HMAC of IdP subject). Partition key for all credentials from one user</li>
					<li><strong>credential_id:</strong> Unique credential identifier (UUID). Sort key for individual credential records</li>
					<li><strong>credential_type:</strong> Type of credential (Student_Credential, Age_Credential, etc.)</li>
					<li><strong>issued_at / expiresAt:</strong> Credential lifecycle timestamps</li>
					<li><strong>revocation_index:</strong> Position in W3C Bitstring Status List for revocation checking</li>
					<li><strong>revoked:</strong> Boolean status flag</li>
				</ul>
			</div>
		</div>

		<div class="schema-card">
			<h3>Credential Entity Schema</h3>
			<p class="schema-description">
				The signed credential delivered to the user's browser (stored in IndexedDB, never on our servers).
			</p>

			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Credential Payload</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "student_id": "G89u28394",
  "email": "anton@oakland.edu",
  "first_name": "Anton",
  "last_name": "Sakhanovych",
  "birthdate": "2000-05-15",
  "custom_claims": {
    "student_status": "enrolled",
    "enrollment_date": "2021-09-01",
    "university": "Oakland University",
    "major": "Computer Science"
  }
}`}</code></pre>
			</div>
		</div>

		<div class="schema-card">
			<h3>Proof Entity Schema</h3>
			<p class="schema-description">
				The zero-knowledge proof generated by the user and sent to the verifier.
			</p>

			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Proof Structure</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "proof_type": "age_over_21",
  "proof": "base64_zkSNARK_proof_bytes",
  "public_inputs": {
    "challenge": "n-0S6_WzA2Mj",                   // Verifier nonce
    "credential_status_index": 94567
  }
}`}</code></pre>
			</div>
		</div>

		<div class="relationships-card">
			<h4>Data Relationships</h4>
			<ul>
				<li><strong>1:N</strong> - One user (subject_id) can have multiple credentials from different sources</li>
				<li><strong>1:N</strong> - One user can generate many different proofs</li>
				<li><strong>1:N</strong> - Each signed credential can be used to generate many proofs</li>
			</ul>
		</div>
	</section>

	<section class="section" id="api">
		<h2>API Specifications</h2>
		<p class="lead">RESTful API endpoints for credential issuance and revocation</p>

		<div class="api-endpoint">
			<div class="endpoint-header">
				<span class="http-method post">POST</span>
				<span class="endpoint-path">/api/credentials/issue</span>
			</div>
			<p class="endpoint-description">
				Issues a BBS+ signed credential after OAuth authentication. Called by the React app after
				receiving the authorization code from Keycloak.
			</p>

			<h4>Request Body</h4>
			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Request</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "authorization_code": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...",
  "redirect_uri": "https://app.zeroverify.com/callback"
}`}</code></pre>
			</div>

			<h4>Response (Success 200)</h4>
			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Response</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "credential": {
    "@context": ["https://www.w3.org/2018/credentials/v1"],
    "type": ["VerifiableCredential", "StudentCredential"],
    "issuer": "did:web:zeroverify.com",
    "issuanceDate": "2025-02-10T20:41:27Z",
    "expirationDate": "2026-02-10T20:41:27Z",
    "credentialSubject": {
      "id": "did:key:z6MkF5rGMoatr...",
      "studentStatus": "enrolled",
      "university": "Oakland University"
    },
    "credentialStatus": {
      "id": "https://api.zeroverify.com/status#94567",
      "type": "BitstringStatusListEntry",
      "statusListIndex": "94567"
    },
    "proof": {
      "type": "BbsBlsSignature2020",
      "created": "2025-02-10T20:41:27Z",
      "proofValue": "base64_bbs_signature..."
    }
  }
}`}</code></pre>
			</div>

			<h4>Error States</h4>
			<div class="error-states">
				<div class="error-state">
					<span class="error-code">400</span>
					<span class="error-desc">Bad Request - Invalid authorization code or missing parameters</span>
				</div>
				<div class="error-state">
					<span class="error-code">401</span>
					<span class="error-desc">Unauthorized - Authentication failed with IdP</span>
				</div>
				<div class="error-state">
					<span class="error-code">409</span>
					<span class="error-desc">Conflict - Active credential already exists for this user</span>
				</div>
				<div class="error-state">
					<span class="error-code">500</span>
					<span class="error-desc">Internal Server Error - Credential signing failed</span>
				</div>
			</div>
		</div>

		<div class="api-endpoint">
			<div class="endpoint-header">
				<span class="http-method post">POST</span>
				<span class="endpoint-path">/api/credentials/revoke</span>
			</div>
			<p class="endpoint-description">
				Submits a credential revocation request. The request is queued and processed in batches.
			</p>

			<h4>Request Body</h4>
			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Request</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "credential_id": "a3f8b2c1-4d5e-6f7a-8b9c-0d1e2f3a4b5c",
  "proof_of_ownership": "base64_zk_proof..."
}`}</code></pre>
			</div>

			<h4>Response (Success 202)</h4>
			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Response</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "status": "queued",
  "message": "Revocation request submitted successfully",
  "estimated_processing_time": "< 10 minutes"
}`}</code></pre>
			</div>
		</div>

		<div class="api-endpoint">
			<div class="endpoint-header">
				<span class="http-method get">GET</span>
				<span class="endpoint-path">/api/status-list</span>
			</div>
			<p class="endpoint-description">
				Returns the W3C Bitstring Status List for revocation checking. This is a public endpoint
				that verifiers download to check credential revocation status locally.
			</p>

			<h4>Response (Success 200)</h4>
			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Response</span>
					<span class="code-lang">JSON</span>
				</div>
				<pre><code>{`{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "type": "BitstringStatusListCredential",
  "issuer": "did:web:zeroverify.com",
  "issued": "2025-02-10T20:41:27Z",
  "credentialSubject": {
    "id": "https://api.zeroverify.com/status",
    "type": "BitstringStatusList",
    "encodedList": "H4sIAAAAAAAA/+3BAQ0AAA..."  // Compressed bitstring
  }
}`}</code></pre>
			</div>
		</div>
	</section>

	<section class="section" id="algorithms">
		<h2>Algorithm Logic</h2>
		<p class="lead">Zero-knowledge proof circuits and cryptographic operations</p>

		<div class="algorithm-card">
			<h3>ZK-SNARK Circuit: Age Verification</h3>
			<p class="algo-description">
				Circom circuit that proves "user is over a certain age" without revealing birthdate.
			</p>

			<div class="code-block">
				<div class="code-header">
					<span class="code-title">age_verification.circom</span>
					<span class="code-lang">Circom</span>
				</div>
				<pre><code>{`pragma circom 2.0.0;

template AgeVerification() {
    // Private inputs (not revealed)
    signal input birthdate;        // YYYYMMDD format
    signal input current_date;     // YYYYMMDD format

    // Public inputs
    signal input min_age;          // Required minimum age (e.g., 21)
    signal input challenge;        // Verifier nonce

    // Public outputs
    signal output is_valid;        // 1 if age >= min_age, 0 otherwise
    signal output challenge_hash;  // Prevents replay attacks

    // Calculate age
    component age_calc = CalculateAge();
    age_calc.birthdate <== birthdate;
    age_calc.current_date <== current_date;

    // Check if age >= minimum required
    component age_check = GreaterEqThan(8);
    age_check.in[0] <== age_calc.age;
    age_check.in[1] <== min_age;

    is_valid <== age_check.out;

    // Bind to challenge to prevent replay
    component hasher = Poseidon(1);
    hasher.inputs[0] <== challenge;
    challenge_hash <== hasher.out;
}

component main = AgeVerification();`}</code></pre>
			</div>

			<div class="algo-explanation">
				<h4>How it works:</h4>
				<ol>
					<li>User provides birthdate and current date as private inputs (never revealed)</li>
					<li>Circuit calculates age from the difference</li>
					<li>Checks if age ≥ minimum required age</li>
					<li>Outputs only a boolean (valid/invalid) and challenge hash</li>
					<li>Verifier learns nothing except "this person meets the age requirement"</li>
				</ol>
			</div>
		</div>

		<div class="algorithm-card">
			<h3>BBS+ Signature Flow</h3>
			<p class="algo-description">
				Selective disclosure signature scheme that enables proving individual attributes.
			</p>

			<div class="flow-steps">
				<div class="flow-step">
					<div class="step-num">1</div>
					<div class="step-content">
						<h4>Credential Signing (Issuer)</h4>
						<p>Issuer signs credential with BBS+ private key. Signature covers all attribute claims.</p>
						<p class="perf-note">Performance: 6-7.5ms per credential</p>
					</div>
				</div>

				<div class="flow-step">
					<div class="step-num">2</div>
					<div class="step-content">
						<h4>Selective Disclosure (User)</h4>
						<p>User creates proof revealing only required attributes (e.g., just "student_status" without name, birthdate, etc.)</p>
						<p class="perf-note">Performance: 1-2ms per proof</p>
					</div>
				</div>

				<div class="flow-step">
					<div class="step-num">3</div>
					<div class="step-content">
						<h4>Proof Verification (Verifier)</h4>
						<p>Verifier checks cryptographic validity using issuer's public key. No access to hidden attributes.</p>
						<p class="perf-note">Performance: ~19ms per proof</p>
					</div>
				</div>
			</div>
		</div>

		<div class="algorithm-card">
			<h3>Revocation Checking Algorithm</h3>
			<p class="algo-description">
				Privacy-preserving revocation using W3C Bitstring Status Lists
			</p>

			<div class="code-block">
				<div class="code-header">
					<span class="code-title">Pseudocode</span>
					<span class="code-lang">Algorithm</span>
				</div>
				<pre><code>{`function checkRevocation(credential, statusList):
    // Extract revocation index from credential
    index = credential.credentialStatus.statusListIndex

    // Download compressed bitstring from S3 (cached locally)
    bitstring = decompress(statusList.encodedList)

    // Check bit at index position
    isRevoked = bitstring[index] == 1

    if isRevoked:
        return REVOKED
    else:
        return ACTIVE

// Privacy property: Verifier downloads entire bitstring
// No query reveals which specific credential is being checked`}</code></pre>
			</div>
		</div>
	</section>
</div>

<style>
	.design-page {
		max-width: 1200px;
	}

	h1 {
		font-size: 3rem;
		margin-bottom: 0.5rem;
	}

	.subtitle {
		color: #8b949e;
		font-size: 1.1rem;
		margin-bottom: 3rem;
	}

	.section {
		margin-bottom: 4rem;
		padding-bottom: 3rem;
		border-bottom: 1px solid #21262d;
	}

	.section:last-child {
		border-bottom: none;
	}

	h2 {
		font-size: 2.5rem;
		margin-bottom: 2rem;
	}

	.lead {
		font-size: 1.2rem;
		color: #8b949e;
		line-height: 1.8;
		margin-bottom: 2rem;
	}

	.schema-card {
		background-color: #161b22;
		border: 1px solid #30363d;
		border-radius: 12px;
		padding: 2rem;
		margin-bottom: 2rem;
	}

	.schema-card h3 {
		font-size: 1.5rem;
		margin-bottom: 1rem;
		color: #00d4ff;
	}

	.schema-description {
		color: #8b949e;
		margin-bottom: 1.5rem;
		line-height: 1.6;
	}

	.code-block {
		background-color: #0d1117;
		border: 1px solid #30363d;
		border-radius: 8px;
		overflow: hidden;
		margin: 1.5rem 0;
	}

	.code-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 0.75rem 1.25rem;
		background-color: #161b22;
		border-bottom: 1px solid #30363d;
		font-size: 0.9rem;
	}

	.code-title {
		color: #c9d1d9;
		font-weight: 600;
		font-size: 0.9rem;
	}

	.code-lang {
		color: #8b949e;
		font-size: 0.85rem;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.code-block pre {
		margin: 0;
		padding: 1.5rem;
		overflow-x: auto;
	}

	.code-block code {
		font-family: 'Courier New', monospace;
		font-size: 0.9rem;
		line-height: 1.6;
		color: #c9d1d9;
	}

	.schema-details {
		margin-top: 2rem;
	}

	.schema-details h4 {
		font-size: 1.1rem;
		margin-bottom: 1rem;
		color: #c9d1d9;
	}

	.schema-details ul {
		list-style: none;
		padding: 0;
	}

	.schema-details li {
		padding: 0.75rem 0;
		color: #8b949e;
		line-height: 1.6;
		border-bottom: 1px solid #21262d;
	}

	.schema-details li:last-child {
		border-bottom: none;
	}

	.schema-details strong {
		color: #9d4edd;
		font-family: 'Courier New', monospace;
		font-size: 0.9rem;
	}

	.relationships-card {
		background-color: #161b22;
		border: 1px solid #30363d;
		border-radius: 8px;
		padding: 1.5rem;
		margin-top: 2rem;
	}

	.relationships-card h4 {
		font-size: 1.1rem;
		margin-bottom: 1rem;
		color: #00d4ff;
	}

	.relationships-card ul {
		list-style: none;
		padding: 0;
		margin: 0;
	}

	.relationships-card li {
		padding: 0.5rem 0;
		color: #8b949e;
		line-height: 1.6;
	}

	.relationships-card strong {
		color: #9d4edd;
		font-weight: 700;
	}

	.api-endpoint {
		background-color: #161b22;
		border: 1px solid #30363d;
		border-radius: 12px;
		padding: 2rem;
		margin-bottom: 3rem;
	}

	.endpoint-header {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-bottom: 1rem;
	}

	.http-method {
		font-weight: 700;
		padding: 0.5rem 1rem;
		border-radius: 6px;
		font-size: 0.85rem;
		letter-spacing: 0.05em;
	}

	.http-method.post {
		background-color: rgba(0, 212, 255, 0.2);
		color: #00d4ff;
	}

	.http-method.get {
		background-color: rgba(157, 78, 221, 0.2);
		color: #9d4edd;
	}

	.endpoint-path {
		font-family: 'Courier New', monospace;
		font-size: 1.1rem;
		color: #c9d1d9;
	}

	.endpoint-description {
		color: #8b949e;
		line-height: 1.7;
		margin-bottom: 2rem;
	}

	.api-endpoint h4 {
		font-size: 1.1rem;
		margin-top: 2rem;
		margin-bottom: 1rem;
		color: #c9d1d9;
	}

	.error-states {
		margin-top: 1.5rem;
	}

	.error-state {
		display: flex;
		gap: 1rem;
		padding: 0.75rem 1rem;
		background-color: #0d1117;
		border: 1px solid #30363d;
		border-radius: 6px;
		margin-bottom: 0.5rem;
	}

	.error-code {
		font-weight: 700;
		color: #ff6b6b;
		font-family: 'Courier New', monospace;
		min-width: 50px;
	}

	.error-desc {
		color: #8b949e;
		line-height: 1.5;
	}

	.algorithm-card {
		background-color: #161b22;
		border: 1px solid #30363d;
		border-radius: 12px;
		padding: 2rem;
		margin-bottom: 3rem;
	}

	.algorithm-card h3 {
		font-size: 1.5rem;
		margin-bottom: 1rem;
		color: #00d4ff;
	}

	.algo-description {
		color: #8b949e;
		margin-bottom: 1.5rem;
		line-height: 1.6;
	}

	.algo-explanation h4 {
		font-size: 1.1rem;
		margin-top: 2rem;
		margin-bottom: 1rem;
		color: #c9d1d9;
	}

	.algo-explanation ol {
		padding-left: 1.5rem;
		color: #8b949e;
	}

	.algo-explanation li {
		margin-bottom: 0.75rem;
		line-height: 1.6;
	}

	.flow-steps {
		margin-top: 2rem;
	}

	.flow-step {
		display: flex;
		gap: 1.5rem;
		margin-bottom: 2rem;
		padding-bottom: 2rem;
		border-bottom: 1px solid #30363d;
	}

	.flow-step:last-child {
		border-bottom: none;
	}

	.step-num {
		flex-shrink: 0;
		width: 50px;
		height: 50px;
		background: linear-gradient(135deg, #00d4ff 0%, #9d4edd 100%);
		border-radius: 50%;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 1.5rem;
		font-weight: 700;
		color: #fff;
	}

	.step-content h4 {
		font-size: 1.2rem;
		margin-bottom: 0.75rem;
		color: #c9d1d9;
	}

	.step-content p {
		color: #8b949e;
		line-height: 1.6;
		margin-bottom: 0.5rem;
	}

	.perf-note {
		color: #9d4edd;
		font-size: 0.9rem;
		font-style: italic;
	}
</style>
